export const GET_CONTACT_LOAD='GET_CONTACT_LOAD'
export const GET_CONTACT_SUCC='GET_CONTACT_SUCC'
export const GET_CONTACT_FAIL='GET_CONTACT_FAIL'

export const DELETE_CONTACT='DELETE_CONTACT'

export const TOGGLE_TRUE='TOGGLE_TRUE'
export const TOGGLE_FALSE='TOGGLE_FALSE'

export const GET_CONTACT='GET_CONTACT'
export const POST_CONTACT='POST_CONTACT'
export const EDIT_CONTACT='EDIT_CONTACT'